#!/bin/bash

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'
# Begin the endless array.
echo '['
# We send an empty first array of blocks to make the loop simpler:
echo '[],'
# Now send blocks with information forever:
case $(hostname) in
  "annoyance")
    CONFIG=i3bar-conkyrc_annoyance
    ;;
  "silence")
    CONFIG=i3bar-conkyrc_silence
    ;;
  *)
    CONFIG=conkyrc-i3
    ;;
esac

exec conky -c $HOME/.i3/$CONFIG
